[package]
name = "common"
version = "0.1.9"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
bincode = "1.3.3"
detour = "0.8.1"
log = "0.4.14"
widestring = "0.5.1"
windows-sys = { version = "0.35.0", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_LibraryLoader",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_Threading",
  "Win32_System_Memory",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_SystemInformation"
] }
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
directories = "4.0.1"
serde_json = "1.0.83"
